name = "Casacore"
uuid = "72bb1062-94f5-49fa-bb69-94b615203ad9"
authors = ["Kirin Shila <me@kiranshila>", "Torrance Hodgson <torrance@pravic.xyz>", "and contributors"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
casacorecxx_jll = "689e2960-4160-5310-ae7f-2d2095288874"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
